# Generated by Django 4.1.3 on 2022-11-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Copilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textarea_old', models.TextField(blank=True, max_length=1000, null=True)),
                ('textarea_new', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
