# Generated by Django 4.1.3 on 2022-11-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='copilot',
            name='progr_lan',
            field=models.TextField(choices=[('Python', 'Python'), ('C++', 'C++'), ('Java', 'Java')], default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
