# Generated by Django 4.1.3 on 2022-11-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_copilot_progr_lan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copilot',
            name='progr_lan',
            field=models.TextField(choices=[('Python', 'Python'), ('Kotlin', 'Kotlin'), ('JavaScript', 'JavaScript')], max_length=1000),
        ),
    ]
